version: '3.8'

services:
  aegis:
    build: .
    ports:
      - "8000:8000"
    networks:
      - kgp_isolated_network
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:alpine
    networks:
      - kgp_isolated_network

  backend:
    image: hashicorp/http-echo
    command: ["-text=SUCCESS: You bypassed the Aegis Shield and reached the hidden core backend!"]
    networks:
      - kgp_isolated_network

networks:
  kgp_isolated_network:
    driver: bridge